#version 450

struct Particle {
  vec4 pos;
  vec4 vel;
  vec4 uv;
  vec4 normal;
};

layout(std430, binding = 0) buffer ParticleIn { Particle particleIn[]; };

layout(local_size_x = 64) in;

layout(binding = 2) uniform UBO {
  float deltaT;
  float density;
  vec4 gravity;
  vec4 lame;
  ivec2 particleCount;
}
params;

struct ElementInfo {
  int elemId;
  float restVol;
  ivec4 pid;
  mat3x3 restShape;
  mat3x3 restShapeInv;
};

layout(std430, binding = 3) buffer LambdaDBuffer { float _lambdaD[]; };

layout(std430, binding = 4) buffer ElementInfoBuffer {
  ElementInfo elementInfo[];
};

layout(std430, binding = 5) buffer ElemParallelSlotsBuffer {
  int elemParallelSlots[];
};

layout(std430, binding = 6) buffer MassesBuffer { float masses[]; };
layout(std430, binding = 7) buffer LambdaHBuffer { float _lambdaH[]; };
layout(std430, binding = 8) buffer FixedPointBuffer { int fixedPoints[]; };

layout(push_constant) uniform PushConsts { uint parallelSetStartIndex; }
pushConsts;

bool isc(uint pid) {
  if (fixedPoints[pid] == 1) {
    return true;
  } else {
    return false;
  }
}
void main() {
  uvec3 id = gl_GlobalInvocationID;
  uint index = id.x;

  if (index < particleIn.length()) {
    float t = 1.0;
    if (particleIn[index].vel.y < particleIn[index].pos.y) {
      t = 0.99;
    }
    particleIn[index].vel.xyz =
        t * float(1 - fixedPoints[index]) *
        (particleIn[index].pos.xyz - particleIn[index].vel.xyz) /
        (params.deltaT);
    if (particleIn[index].pos.y <= -1.0 && particleIn[index].vel.y < 0.0) {
      particleIn[index].vel.y = -0.3 * particleIn[index].vel.y;
      particleIn[index].pos.y = -1.0;
    }
  }
}
