#version 450

struct Particle {
  vec4 pos;
  vec4 vel;
  vec4 uv;
  vec4 normal;
};

layout(std430, binding = 0) buffer ParticleIn { Particle particleIn[]; };

layout(local_size_x = 64) in;

layout(binding = 2) uniform UBO {
  float deltaT;
  float density;
  vec4 gravity;
  vec4 lame;
  ivec2 particleCount;
  vec4 ground;
}
params;

layout(std430, binding = 3) buffer LambdaDBuffer { float _lambdaD[]; };
layout(std430, binding = 4) buffer ElementInfoBuffer {
  vec4 elementInfoPadding[];
};
layout(std430, binding = 5) buffer ElemParallelSlotsBuffer {
  int elemParallelSlots[];
};
layout(std430, binding = 6) buffer MassesBuffer { float masses[]; };
layout(std430, binding = 7) buffer LambdaHBuffer { float _lambdaH[]; };
layout(std430, binding = 8) buffer FixedPointBuffer { int fixedPoints[]; };

layout(push_constant) uniform PushConsts { uint parallelSetStartIndex; }
pushConsts;

void main() {
  const uint index = gl_GlobalInvocationID.x;
  if (index >= particleIn.length() || fixedPoints[index] != 0 ||
      params.ground.z <= 0.5) {
    return;
  }

  // Project to the feasible half-space C(x) = y - groundHeight >= 0.
  particleIn[index].pos.y = max(particleIn[index].pos.y, params.ground.x);
}
