#version 450

struct Particle {
  vec4 pos;
  vec4 vel;
  vec4 uv;
  vec4 normal;
};

layout(std430, binding = 0) buffer ParticleIn { Particle particleIn[]; };

layout(local_size_x = 64) in;

layout(binding = 2) uniform UBO {
  float deltaT;
  float density;
  float damping;
  vec4 gravity;
  vec4 lame;
  ivec2 particleCount;
  vec4 ground;
}
params;

struct ElementInfo {
  int elemId;
  float restVol;
  ivec4 pid;
  mat3x3 restShape;
  mat3x3 restShapeInv;
};

layout(std430, binding = 3) buffer LambdaBuffer { float _lambda[]; };

layout(std430, binding = 4) buffer ElementInfoBuffer {
  ElementInfo elementInfo[];
};

layout(std430, binding = 5) buffer ElemParallelSlotsBuffer {
  int elemParallelSlots[];
};

layout(std430, binding = 6) buffer MassesBuffer { float masses[]; };
layout(std430, binding = 8) buffer FixedPointBuffer { int fixedPoints[]; };

layout(push_constant) uniform PushConsts { uint parallelSetStartIndex; }
pushConsts;

bool isc(uint pid) {
  if (fixedPoints[pid] == 1) {
    return true;
  } else {
    return false;
  }
}
void main() {
  uvec3 id = gl_GlobalInvocationID;
  uint index = id.x;
  uint numParticles =
      uint(params.particleCount.x) * uint(params.particleCount.y);
  if (index < particleIn.length()) {
    vec3 dx = particleIn[index].vel.xyz * (params.deltaT);
    dx += params.gravity.xyz * (params.deltaT) * (params.deltaT);
    particleIn[index].vel = particleIn[index].pos;
    particleIn[index].pos.xyz += float(1.0 - fixedPoints[index]) * dx;
  }

  if (index < _lambda.length()) {
    _lambda[index] = 0;
  }
}
