apply plugin: 'com.android.application'
apply from: '../gradle/outputfilename.gradle'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId 'de.saschawillems.xpbdvsrid3d'
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName '1.0'
        ndk { abiFilters rootProject.ext.abiFilters }
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++20'
                arguments '-DANDROID_STL=c++_shared', '-DANDROID_TOOLCHAIN=clang', '-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON'
            }
        }
    }
    sourceSets {
        main {
            assets.srcDirs = ['assets']
            manifest.srcFile '../riddfmb3d/src/main/AndroidManifest.xml'
            java.srcDirs = ['../riddfmb3d/src/main/java']
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    externalNativeBuild { cmake { path 'CMakeLists.txt' } }
}

task copyTask {
    copy { from '../../common/res/drawable'; into 'src/main/res/drawable'; include 'icon.png' }
    copy { from rootProject.ext.shaderPath + 'glsl/base'; into 'assets/shaders/glsl/base'; include '*.spv' }
    copy { from rootProject.ext.shaderPath + 'glsl/xpbdjacobi3d'; into 'assets/shaders/glsl/xpbdjacobi3d'; include '*.spv' }
    copy { from rootProject.ext.shaderPath + 'glsl/riddfmb3d'; into 'assets/shaders/glsl/riddfmb3d'; include '*.spv' }
    copy { from rootProject.ext.assetPath + 'models'; into 'assets/models'; include 'beam3d.vtk' }
    copy { from rootProject.ext.assetPath + 'configs'; into 'assets/configs'; include 'solver_comparison.json' }
}
preBuild.dependsOn copyTask
