#version 450

struct Particle {
	vec4 pos;
	vec4 vel;
	vec4 uv;
	vec4 normal;
};

layout(std430, binding = 0) buffer ParticleIn {
	Particle particleIn[ ];
};

layout(std430, binding = 1) buffer ParticleOut {
	Particle particleOut[ ];
};

// todo: use shared memory to speed up calculation

layout (local_size_x = 10) in;

layout (binding = 2) uniform UBO 
{
	float deltaT;
	float particleMass;
	float springStiffness;
	float damping;
	float restDistH;
	float restDistV;
	float restDistD;
	float sphereRadius;
	vec4 spherePos;
	vec4 gravity;
	ivec2 particleCount;
} params;

struct ElementInfo {
  int elemId;
  ivec2 pid;
  float restLength;
};

layout(std430, binding = 3) buffer LambdaBuffer {
  float _lambda[];
};

layout(std430, binding = 4) buffer ElementInfoBuffer {
  ElementInfo elementInfo[];
};

layout(std430, binding = 5) buffer ElemParallelSlotsBuffer {
  int elemParallelSlots[];
};

layout (push_constant) uniform PushConsts {
	uint computeStage;
	uint parallelSetStartIndex;
} pushConsts;

bool isc(uint pid) {
	//return false;
	return pid == 0 || pid == 59;
}

void main() 
{
	uvec3 id = gl_GlobalInvocationID; 
	uint index = id.x;
	vec3 pos = particleIn[index].pos.xyz;
	uint numParticles = params.particleCount.x * params.particleCount.y;
	if(pushConsts.computeStage == 0) {
		if (index >= numParticles) 
			return;
		if (index < particleIn.length()) {
 			vec3 dx = particleIn[index].vel.xyz * (params.deltaT); 
    		dx += params.gravity.xyz * (params.deltaT) * (params.deltaT); 
   			particleIn[index].vel = particleIn[index].pos;
    		particleIn[index].pos.xyz +=  float(1.0-float(isc(index))) * dx;
		}
		if (index < _lambda.length()) {
			_lambda[index] = 0.0;
		}
	}
	else if(pushConsts.computeStage == 1) {
		 int st = elemParallelSlots[pushConsts.parallelSetStartIndex];
  		 int ed = elemParallelSlots[pushConsts.parallelSetStartIndex + 1];
         if (index + st >= ed)
            return;
		const int elemId = int(index) + st;
  		const ElementInfo elemInfo = elementInfo[elemId];

 		const float invDt = float(1) / (params.deltaT);
  		const float invDt2 = invDt * invDt;

  		mat2x3 localV;
  		vec2 localMassInv;
        localV[0] = particleIn[elemInfo.pid[0]].pos.xyz;
        localV[1] = particleIn[elemInfo.pid[1]].pos.xyz;
        localMassInv[0] = 1.0 / params.particleMass;
        localMassInv[1] = 1.0 / params.particleMass;
        float local_alpha = float(1.0) / (params.springStiffness * invDt2);
        float DLambda = -(length(localV[1] - localV[0]) - elemInfo.restLength) /
                  (localMassInv[0] + localMassInv[1] + local_alpha);
        _lambda[elemId] += DLambda;

        particleIn[elemInfo.pid[0]].pos.xyz += 
        float(1.0-float(isc(elemInfo.pid[0]))) * localMassInv[0] * DLambda * normalize(localV[0] - localV[1]);
        particleIn[elemInfo.pid[1]].pos.xyz += 
        float(1.0-float(isc(elemInfo.pid[1]))) * localMassInv[1] * DLambda * normalize(localV[1] - localV[0]);
	}
	else if(pushConsts.computeStage == 2) {
		if (index >= numParticles) 
			return;
		if (index < particleIn.length()) {
			particleIn[index].vel.xyz = float(1 - float(isc(index))) *
                     (particleIn[index].pos.xyz - particleIn[index].vel.xyz) / (params.deltaT);
			particleOut[index].pos = particleIn[index].pos;
			particleOut[index].vel = particleIn[index].vel;
		}
		// 	vec3 sphereDist = particleOut[index].pos.xyz - params.spherePos.xyz;
		// if (length(sphereDist) < params.sphereRadius + 0.01) {
		// 	// If the particle is inside the sphere, push it to the outer radius
		// 	particleOut[index].pos.xyz = params.spherePos.xyz + normalize(sphereDist) * (params.sphereRadius + 0.01);		
		// // Cancel out velocity
		// 	particleOut[index].vel = vec4(0.0);
		// }
		vec3 normal = vec3(0.0);
		vec3 a, b, c;
		if (id.y > 0) {
			if (id.x > 0) {
				a = particleIn[index - 1].pos.xyz - pos;
				b = particleIn[index - params.particleCount.x - 1].pos.xyz - pos;
				c = particleIn[index - params.particleCount.x].pos.xyz - pos;
				normal += cross(a,b) + cross(b,c);
			}
			if (id.x < params.particleCount.x - 1) {
				a = particleIn[index - params.particleCount.x].pos.xyz - pos;
				b = particleIn[index - params.particleCount.x + 1].pos.xyz - pos;
				c = particleIn[index + 1].pos.xyz - pos;
				normal += cross(a,b) + cross(b,c);
			}
		}
		if (id.y < params.particleCount.y - 1) {
			if (id.x > 0) {
				a = particleIn[index + params.particleCount.x].pos.xyz - pos;
				b = particleIn[index + params.particleCount.x - 1].pos.xyz - pos;
				c = particleIn[index - 1].pos.xyz - pos;
				normal += cross(a,b) + cross(b,c);
			}
			if (id.x < params.particleCount.x - 1) {
				a = particleIn[index + 1].pos.xyz - pos;
				b = particleIn[index + params.particleCount.x + 1].pos.xyz - pos;
				c = particleIn[index + params.particleCount.x].pos.xyz - pos;
				normal += cross(a,b) + cross(b,c);
			}
		}
		particleOut[index].normal = vec4(normalize(normal), 0.0f);
		particleIn[index].normal = vec4(normalize(normal), 0.0f);
	}

}