#version 450

layout(local_size_x = 64) in;

struct Particle {
  vec4 pos;
  vec4 vel;
  vec4 uv;
  vec4 normal;
};
layout(std430, binding = 0) buffer Particles { Particle particles[]; };
layout(std140, binding = 1) uniform Params {
  float deltaT;
  float relaxation;
  float lameLambda;
  float lameMu;
  vec4 gravity;
  float damping;
  uint particleCount;
  uint edgeCount;
  uint elementCount;
} params;
layout(std430, binding = 3) readonly buffer FixedPoints { int fixedPoints[]; };
layout(std430, binding = 7) readonly buffer VolumeCorrections { vec4 corrections[]; };
layout(std430, binding = 10) readonly buffer VolumeOffsets { int offsets[]; };
layout(std430, binding = 11) readonly buffer VolumeCorrectionIndices { int indices[]; };

void main() {
  uint particle = gl_GlobalInvocationID.x;
  if (particle >= params.particleCount || fixedPoints[particle] != 0) {
    return;
  }
  vec3 sum = vec3(0.0);
  for (int entry = offsets[particle]; entry < offsets[particle + 1]; ++entry) {
    sum += corrections[indices[entry]].xyz;
  }
  particles[particle].pos.xyz += params.relaxation * sum;
}
